apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: ssss
namespace: ssss
resources:
- secrets.yaml
- namespace.yaml
- backend.yaml
- frontend.yaml
- ingress.yaml
images:
- name: ghcr.io/hvaprojects/ssss_frontend
  newName: ghcr.io/hvaprojects/ssss_frontend # {"$imagepolicy":"flux-system:ssss-frontend:name"}
  newTag: main-b2f5b7e-1620584477 # {"$imagepolicy": "flux-system:ssss-frontend:tag"}
- name: ghcr.io/hvaprojects/ssss_backend
  newName: ghcr.io/hvaprojects/ssss_backend # {"$imagepolicy":"flux-system:ssss-backend:name"}
  newTag: main-8439ec1-20210509041822864 # {"$imagepolicy": "flux-system:ssss-backend:tag"}
